[build]
  command = "corepack enable && pnpm install --frozen-lockfile && pnpm rebuild better-sqlite3 && pnpm run dev:prepare && pnpm nuxt build playground"
  publish = "playground/dist"
  functions = "playground/.netlify/functions-internal"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
