[build]
  command = "corepack enable && pnpm install --frozen-lockfile && pnpm run dev:prepare && pnpm nuxt build playground"
  publish = "playground/.output/public"

[build.environment]
  NODE_VERSION = "20"
