[build]
  command = "corepack enable && pnpm install --frozen-lockfile && cd playground && pnpm install --frozen-lockfile && cd .. && pnpm run dev:prepare && pnpm nuxt build playground"
  publish = "playground/dist"
  functions = "playground/.netlify/functions-internal"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max-old-space-size=4096"
