import {
  defineNuxtModule,
  createResolver,
  addServerHandler,
  addImportsDir,
  addTypeTemplate,
} from '@nuxt/kit'
import { defu } from 'defu'
import type { ModuleOptions } from './runtime/types'

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-reviews',
    configKey: 'reviews',
    compatibility: {
      nuxt: '>=3.10.0',
    },
  },
  defaults: {
    providers: {},
    cacheTTL: 3600,
    cache: true,
    maxReviews: 50,
    minRating: undefined,
    apiPrefix: '/api/_reviews',
  },
  setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)

    // Inject runtime config (server-only for API keys)
    nuxt.options.runtimeConfig.reviews = defu(
      nuxt.options.runtimeConfig.reviews as Record<string, unknown>,
      {
        providers: options.providers,
        cacheTTL: options.cacheTTL,
        cache: options.cache,
        maxReviews: options.maxReviews,
        minRating: options.minRating,
        moderation: options.moderation,
      },
    )

    // Public runtime config (safe for client)
    nuxt.options.runtimeConfig.public.reviews = defu(
      nuxt.options.runtimeConfig.public.reviews as Record<string, unknown>,
      {
        apiPrefix: options.apiPrefix,
        providers: Object.keys(options.providers),
        defaultLanguage: options.defaultLanguage,
      },
    )

    // Register server API routes
    const apiPrefix = options.apiPrefix || '/api/_reviews'

    addServerHandler({
      route: `${apiPrefix}/:provider`,
      handler: resolve('./runtime/server/api/reviews/[provider].get'),
    })

    addServerHandler({
      route: `${apiPrefix}`,
      handler: resolve('./runtime/server/api/reviews/index.get'),
    })

    // Auto-import composables
    addImportsDir(resolve('./runtime/composables'))

    // Type augmentation for nuxt.config
    addTypeTemplate({
      filename: 'types/nuxt-reviews.d.ts',
      getContents: () => `
// Generated by nuxt-reviews module
import type { ModuleOptions } from 'nuxt-reviews/dist/runtime/types'

declare module 'nuxt/schema' {
  interface NuxtConfig {
    reviews?: Partial<ModuleOptions>
  }
  interface PublicRuntimeConfig {
    reviews: {
      apiPrefix: string
      providers: string[]
      defaultLanguage?: string
    }
  }
  interface RuntimeConfig {
    reviews: {
      providers: ModuleOptions['providers']
      cacheTTL: number
      cache: boolean
      maxReviews: number
    }
  }
}

export {}
`,
    })
  },
})
